/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.babystore;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TestEnv
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\bill.png")); // NOI18N
        jLabel1.setText("  Bill");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 29, 695, 53);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("show the bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 113, 187, 39);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setText("count of bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 158, 130, 39);

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton3.setText("search for an bill");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 250, 187, 39);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Bill_ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 210, 59, 26);

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 312, 100, 40);

        jButton5.setBackground(new java.awt.Color(255, 204, 204));
        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 360, 100, 38);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill_ID", "Bill_name", "Bill_date", "payment", "descount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(232, 113, 452, 295);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(70, 210, 116, 26);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 162, 40, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try {
           DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
           String ur1="jdbc:oracle:thin:@localhost:1521:xe";
          Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
              con.setAutoCommit(false);
             Statement stmt=con.createStatement();
             int number = Integer.parseInt(jTextField3.getText());
             
             String sql="select * from bill where bill_ID="+number+"";
             ResultSet rs= stmt.executeQuery(sql);
             
             while(rs.next()){
                String bill_ID= String.valueOf(rs.getInt("bill_ID"));
                String bill_name=rs.getString("bill_name");
                  String date= rs.getString("BILL_DATE");
                String payment= String.valueOf(rs.getDouble("PAYMENT"));
                String descount= String.valueOf(rs.getDouble("DESCOUNT"));
               String tbdata[] = {bill_ID,bill_name,date, payment,descount};
                DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
               tblModel.addRow(tbdata);
                System.out.println(Arrays.toString(tbdata));
                
                
             
             }
            
          
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         mainapplication o=new  mainapplication();
        o.setVisible(true);
        o.setBounds(0, 0, 700, 617);
        o.setResizable(false);
        o.setTitle("STORE");
        o.setDefaultCloseOperation(mainapplication.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
           DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
           String ur1="jdbc:oracle:thin:@localhost:1521:xe";
          Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
              con.setAutoCommit(false);
             Statement stmt=con.createStatement();
             String sql="select * from bill";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                String bill_ID= String.valueOf(rs.getInt("bill_ID"));
                String bill_name=rs.getString("bill_name");
                  String date= rs.getString("BILL_DATE");
                String payment= String.valueOf(rs.getDouble("PAYMENT"));
                String descount= String.valueOf(rs.getDouble("DESCOUNT"));
               String tbdata[] = {bill_ID,bill_name,date, payment,descount};
                DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
               tblModel.addRow(tbdata);
             }
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
          jTable1.setModel(new DefaultTableModel(null,new String[]{"bill_ID","bill_name","bill_date","payment","descount"}));
         jTextField1.setText("");
         jTextField3.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
       try {
           DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
           String ur1="jdbc:oracle:thin:@localhost:1521:xe";
          Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
            Statement stmt=con.createStatement();
            int count=0;
             String sql="select * from bill";
             ResultSet rs= stmt.executeQuery(sql);
             
             while(rs.next()){
             count++;
                 
             }
              String countt= String.valueOf((count));
             jTextField1.setText(countt);
            
            // ResultSet rs= stmt.executeQuery(sql);
            
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
