/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.babystore;
import static com.mycompany.babystore.mainapplication.ID;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TestEnv
 */
public class clothesJfram extends javax.swing.JFrame {

    /**
     * Creates new form clothesJfram
     */
    mainappuser D=new mainappuser();
    public static String id;
    public clothesJfram(String pc1,String pc2,String pc3,String pc4,String pc5,String pc6) {
        initComponents();
         price_c1.setText(pc1);
          price_c2.setText(pc2);
           price_c3.setText(pc3);
            price_c4.setText(pc4);
             price_c5.setText(pc5);
              price_c6.setText(pc6);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id_c1 = new javax.swing.JLabel();
        id_c2 = new javax.swing.JLabel();
        id_c3 = new javax.swing.JLabel();
        id_c4 = new javax.swing.JLabel();
        id_c5 = new javax.swing.JLabel();
        id_c6 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        price_c1 = new javax.swing.JTextField();
        c2 = new javax.swing.JLabel();
        price_c2 = new javax.swing.JTextField();
        c3 = new javax.swing.JLabel();
        price_c3 = new javax.swing.JTextField();
        price_c4 = new javax.swing.JTextField();
        c4 = new javax.swing.JLabel();
        price_c5 = new javax.swing.JTextField();
        c5 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        price_c6 = new javax.swing.JTextField();
        add_to_cartc1 = new javax.swing.JButton();
        add_to_cartc2 = new javax.swing.JButton();
        add_to_cartc3 = new javax.swing.JButton();
        add_to_cartc4 = new javax.swing.JButton();
        add_to_cartc5 = new javax.swing.JButton();
        add_to_cartc6 = new javax.swing.JButton();
        shoppingcart = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\6.jpeg")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 150, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\2.jpeg")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 150, 150));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\3.jpeg")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 150, 150));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\5.jpeg")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 150, 150));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\4.jpeg")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 150, 150));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\1.jpeg")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 150, 150));

        id_c1.setText("110011");
        getContentPane().add(id_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 50, -1));

        id_c2.setText("120011");
        getContentPane().add(id_c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 50, -1));

        id_c3.setText("130011");
        getContentPane().add(id_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 50, -1));

        id_c4.setText("150011");
        getContentPane().add(id_c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 50, -1));

        id_c5.setText("160011");
        getContentPane().add(id_c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 50, -1));

        id_c6.setText("170011");
        getContentPane().add(id_c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 50, -1));

        c1.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        c1.setText("Baby Jumpsuit");
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 150, 30));

        price_c1.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        price_c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_c1ActionPerformed(evt);
            }
        });
        getContentPane().add(price_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, 30));

        c2.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        c2.setText("Suit");
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 150, 30));

        price_c2.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        price_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_c2ActionPerformed(evt);
            }
        });
        getContentPane().add(price_c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 80, 30));

        c3.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        c3.setText("Boy Training");
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 150, 30));

        price_c3.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        price_c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_c3ActionPerformed(evt);
            }
        });
        getContentPane().add(price_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 80, 30));

        price_c4.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        price_c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_c4ActionPerformed(evt);
            }
        });
        getContentPane().add(price_c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 80, 30));

        c4.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        c4.setText("Girl Dress1");
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 150, 30));

        price_c5.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        price_c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_c5ActionPerformed(evt);
            }
        });
        getContentPane().add(price_c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 80, 30));

        c5.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        c5.setText("Girl Dress2");
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 150, 30));

        c6.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        c6.setText("Pejama");
        getContentPane().add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 150, 30));

        price_c6.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        price_c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_c6ActionPerformed(evt);
            }
        });
        getContentPane().add(price_c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 80, 30));

        add_to_cartc1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\add to cart.png")); // NOI18N
        add_to_cartc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_to_cartc1ActionPerformed(evt);
            }
        });
        getContentPane().add(add_to_cartc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 50, 50));

        add_to_cartc2.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\add to cart.png")); // NOI18N
        add_to_cartc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_to_cartc2ActionPerformed(evt);
            }
        });
        getContentPane().add(add_to_cartc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 50, 50));

        add_to_cartc3.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\add to cart.png")); // NOI18N
        add_to_cartc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_to_cartc3ActionPerformed(evt);
            }
        });
        getContentPane().add(add_to_cartc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 50, 50));

        add_to_cartc4.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\add to cart.png")); // NOI18N
        add_to_cartc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_to_cartc4ActionPerformed(evt);
            }
        });
        getContentPane().add(add_to_cartc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 50, 50));

        add_to_cartc5.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\add to cart.png")); // NOI18N
        add_to_cartc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_to_cartc5ActionPerformed(evt);
            }
        });
        getContentPane().add(add_to_cartc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 50, 50));

        add_to_cartc6.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\add to cart.png")); // NOI18N
        add_to_cartc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_to_cartc6ActionPerformed(evt);
            }
        });
        getContentPane().add(add_to_cartc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 50, 50));

        shoppingcart.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\cart.jpg")); // NOI18N
        shoppingcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoppingcartActionPerformed(evt);
            }
        });
        getContentPane().add(shoppingcart, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 60, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\back.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\nnbc.jpg")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -140, 710, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void price_c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_c1ActionPerformed

    private void price_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_c2ActionPerformed

    private void price_c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_c3ActionPerformed

    private void price_c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_c4ActionPerformed

    private void price_c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_c5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_c5ActionPerformed

    private void price_c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_c6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_c6ActionPerformed

    private void shoppingcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoppingcartActionPerformed
        // TODO add your handling code here:
        
        shoppingCart c = new shoppingCart();
        c.setVisible(true);
        c.setBounds(0, 0, 800, 750);
        c.setResizable(false);
        c.setTitle("Shopping Cart");
        c.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         this.setVisible(false);
    }//GEN-LAST:event_shoppingcartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
       mainappuser o=new  mainappuser();
        o.setVisible(true);
        o.setBounds(0, 0, 650, 520);
        o.setResizable(false);
        o.setTitle("product");
        o.setDefaultCloseOperation(product.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        jLabel6.setToolTipText("Winter jumpsuit for boys");
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
         jLabel3.setToolTipText("Beige suit for children");
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
         jLabel4.setToolTipText("Cotton clothes that are comfortable for the movement of children and of high quality");
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
                 jLabel5.setToolTipText("Beautiful cotton dress for girls");

    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
         jLabel2.setToolTipText("Beautiful cotton dress for girls");
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
         jLabel7.setToolTipText("Cotton clothes that are comfortable for the movement high quality, and a special price");
    }//GEN-LAST:event_jLabel7MouseEntered

    private void add_to_cartc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_to_cartc1ActionPerformed
        // TODO add your handling code here:
       
        try {
           id=D.ID1;
           
                DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                String ur1="jdbc:oracle:thin:@localhost:1521:xe";
                Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
             Statement stmt=con.createStatement();
             String sql="select * from product where PRODUCT_ID="+110011+"";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                 String pro_ID= String.valueOf(rs.getInt("PRODUCT_ID"));
                  String name=rs.getString("PRODUCT_NAME");
                 String price= String.valueOf(rs.getDouble("PRODUCT_PRICE"));
                  String teyp=rs.getString("PROD_TYPE");
                  String sqlc="insert into cart values(S1.nextval,"+pro_ID+",'"+name+"',"+ price+",'"+teyp+"',"+id+")";
                  PreparedStatement pstmt=con.prepareStatement(sqlc);
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null,"DONE TO ADD ");
             }
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
    }//GEN-LAST:event_add_to_cartc1ActionPerformed

    private void add_to_cartc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_to_cartc2ActionPerformed
        // TODO add your handling code here:
        try {
           id=D.ID1;
           
                DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                String ur1="jdbc:oracle:thin:@localhost:1521:xe";
                Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
             Statement stmt=con.createStatement();
             String sql="select * from product where PRODUCT_ID="+120011+"";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                 String pro_ID= String.valueOf(rs.getInt("PRODUCT_ID"));
                  String name=rs.getString("PRODUCT_NAME");
                 String price= String.valueOf(rs.getDouble("PRODUCT_PRICE"));
                  String teyp=rs.getString("PROD_TYPE");
                  String sqlc="insert into cart values(S1.nextval,"+pro_ID+",'"+name+"',"+ price+",'"+teyp+"',"+id+")";
                  PreparedStatement pstmt=con.prepareStatement(sqlc);
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null,"DONE TO ADD ");
             }
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
                
    }//GEN-LAST:event_add_to_cartc2ActionPerformed

    private void add_to_cartc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_to_cartc3ActionPerformed
        // TODO add your handling code here:
        try {
           id=D.ID1;
           
                DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                String ur1="jdbc:oracle:thin:@localhost:1521:xe";
                Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
             Statement stmt=con.createStatement();
             String sql="select * from product where PRODUCT_ID="+130011+"";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                 String pro_ID= String.valueOf(rs.getInt("PRODUCT_ID"));
                  String name=rs.getString("PRODUCT_NAME");
                 String price= String.valueOf(rs.getDouble("PRODUCT_PRICE"));
                  String teyp=rs.getString("PROD_TYPE");
                  String sqlc="insert into cart values(S1.nextval,"+pro_ID+",'"+name+"',"+ price+",'"+teyp+"',"+id+")";
                  PreparedStatement pstmt=con.prepareStatement(sqlc);
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null,"DONE TO ADD ");
             }
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
               
    }//GEN-LAST:event_add_to_cartc3ActionPerformed

    private void add_to_cartc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_to_cartc4ActionPerformed
        // TODO add your handling code here:
        try {
           id=D.ID1;
           
                DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                String ur1="jdbc:oracle:thin:@localhost:1521:xe";
                Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
             Statement stmt=con.createStatement();
             String sql="select * from product where PRODUCT_ID="+150011+"";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                 String pro_ID= String.valueOf(rs.getInt("PRODUCT_ID"));
                  String name=rs.getString("PRODUCT_NAME");
                 String price= String.valueOf(rs.getDouble("PRODUCT_PRICE"));
                  String teyp=rs.getString("PROD_TYPE");
                  String sqlc="insert into cart values(S1.nextval,"+pro_ID+",'"+name+"',"+ price+",'"+teyp+"',"+id+")";
                  PreparedStatement pstmt=con.prepareStatement(sqlc);
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null,"DONE TO ADD ");
             }
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
                
    }//GEN-LAST:event_add_to_cartc4ActionPerformed

    private void add_to_cartc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_to_cartc5ActionPerformed
        // TODO add your handling code here:
        try {
           id=D.ID1;
           
                DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                String ur1="jdbc:oracle:thin:@localhost:1521:xe";
                Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
             Statement stmt=con.createStatement();
             String sql="select * from product where PRODUCT_ID="+160011+"";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                 String pro_ID= String.valueOf(rs.getInt("PRODUCT_ID"));
                  String name=rs.getString("PRODUCT_NAME");
                 String price= String.valueOf(rs.getDouble("PRODUCT_PRICE"));
                  String teyp=rs.getString("PROD_TYPE");
                  String sqlc="insert into cart values(S1.nextval,"+pro_ID+",'"+name+"',"+ price+",'"+teyp+"',"+id+")";
                  PreparedStatement pstmt=con.prepareStatement(sqlc);
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null,"DONE TO ADD ");
             }
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
              
    }//GEN-LAST:event_add_to_cartc5ActionPerformed

    private void add_to_cartc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_to_cartc6ActionPerformed
        // TODO add your handling code here:
        try {
           id=D.ID1;
           
                DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                String ur1="jdbc:oracle:thin:@localhost:1521:xe";
                Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
             Statement stmt=con.createStatement();
             String sql="select * from product where PRODUCT_ID="+170011+"";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                 String pro_ID= String.valueOf(rs.getInt("PRODUCT_ID"));
                  String name=rs.getString("PRODUCT_NAME");
                 String price= String.valueOf(rs.getDouble("PRODUCT_PRICE"));
                  String teyp=rs.getString("PROD_TYPE");
                  String sqlc="insert into cart values(S1.nextval,"+pro_ID+",'"+name+"',"+ price+",'"+teyp+"',"+id+")";
                  PreparedStatement pstmt=con.prepareStatement(sqlc);
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null,"DONE TO ADD ");
             }
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
              
    }//GEN-LAST:event_add_to_cartc6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clothesJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clothesJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clothesJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clothesJfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new clothesJfram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_to_cartc1;
    private javax.swing.JButton add_to_cartc2;
    private javax.swing.JButton add_to_cartc3;
    private javax.swing.JButton add_to_cartc4;
    private javax.swing.JButton add_to_cartc5;
    private javax.swing.JButton add_to_cartc6;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel id_c1;
    private javax.swing.JLabel id_c2;
    private javax.swing.JLabel id_c3;
    private javax.swing.JLabel id_c4;
    private javax.swing.JLabel id_c5;
    private javax.swing.JLabel id_c6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField price_c1;
    private javax.swing.JTextField price_c2;
    private javax.swing.JTextField price_c3;
    private javax.swing.JTextField price_c4;
    private javax.swing.JTextField price_c5;
    private javax.swing.JTextField price_c6;
    private javax.swing.JButton shoppingcart;
    // End of variables declaration//GEN-END:variables
}
