/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.babystore;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author TestEnv
 */
public class creatuser extends javax.swing.JFrame {

    /**
     * Creates new form creatuser
     */
    public creatuser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\pp.jpeg")); // NOI18N
        jLabel1.setText("  User Information");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 48, 374, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("ID User");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 109, 82, 25);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 149, 82, 25);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("Sacond Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(6, 189, 82, 25);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setText("Last Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(6, 229, 82, 25);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("phone");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(6, 269, 82, 25);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(6, 308, 82, 25);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(106, 106, 274, 28);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(106, 146, 274, 28);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(106, 186, 274, 28);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(106, 226, 274, 28);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(106, 266, 274, 28);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(106, 306, 274, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(6, 385, 117, 26);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel9.setText("City: ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(39, 418, 41, 21);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(86, 418, 103, 23);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel10.setText("Street: ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(195, 417, 63, 22);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(264, 418, 116, 22);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel11.setText("Usar Name");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(6, 481, 86, 32);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(110, 482, 270, 32);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel12.setText("Password");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(6, 532, 86, 30);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(110, 533, 270, 30);

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        jButton1.setText("cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 620, 100, 36);

        jButton2.setBackground(new java.awt.Color(0, 102, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(185, 620, 100, 36);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("بسم الله الرحمن الرحيم");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(116, 12, 181, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\mmmm.jpg")); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 440, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String ur1="jdbc:oracle:thin:@localhost:1521:xe";
              Connection con = DriverManager.getConnection(ur1, "c##nancysawa", "654321");
            Statement stmt=con.createStatement();
            String strStmt="insert into USERR values(?,?,?,?,?,?)";
            PreparedStatement pstmt=con.prepareStatement(strStmt);
            pstmt.setInt(1, Integer.parseInt(jTextField1.getText()));
            pstmt.setString(2, jTextField2.getText());
            pstmt.setString(3, jTextField3.getText());
            pstmt.setString(4, jTextField4.getText());
              pstmt.setInt(5, Integer.parseInt(jTextField5.getText()));
            pstmt.setString(6, jTextField6.getText());
             String sttrStmt="insert into ADDRESS values(?,?,?)";
               PreparedStatement pstm=con.prepareStatement(sttrStmt);
                  pstm.setInt(1, Integer.parseInt(jTextField1.getText()));
                   pstm.setString(2, jTextField7.getText());
                   pstm.setString(3, jTextField8.getText());
                    String strrStmt="insert into LOGIN values(?,?)";
                   PreparedStatement ps=con.prepareStatement(strrStmt);
                   ps.setString(1, jTextField9.getText());
                  ps.setString(2, jTextField10.getText());
                   String strsStmt="insert into VERIFYU values(?,?)";
                   PreparedStatement pst=con.prepareStatement(strsStmt);
                    pst.setInt(1, Integer.parseInt(jTextField1.getText()));
                   pst.setString(2, jTextField9.getText());

              pstmt.executeUpdate();
              pstm.executeUpdate();
               ps.executeUpdate();
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"DONE CREAT user  Thank you ");
              jTextField1.setText("");
              jTextField2.setText("");
              jTextField3.setText("");
              jTextField4.setText("");
              jTextField5.setText("");
              jTextField6.setText("");
              jTextField7.setText(""); 
              jTextField8.setText("");
              jTextField9.setText("");
              jTextField10.setText("");
              
        } 
        
        
        catch (SQLException ex) {
            Logger.getLogger(creatuser.class.getName()).log(Level.SEVERE, null, ex);
        
        }      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(creatuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(creatuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(creatuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(creatuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new creatuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
