/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.babystore;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TestEnv
 */
public class login extends javax.swing.JFrame {
    
    public static  String pass1 = null;
    public static  String name = null;
    public static  String passa = null;
    public static  String name1 = null;
    public login() {
        initComponents();
        
       
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setBackground(new java.awt.Color(0, 153, 204));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("User Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 260, 163, 43);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 310, 163, 41);

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 350, 163, 43);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Creat New User");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 530, 139, 43);

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign UP");
        jButton1.setActionCommand("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(273, 570, 130, 44);

        jButton2.setBackground(new java.awt.Color(0, 102, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 450, 100, 44);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Baby  ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 94, 43);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Store");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 90, 85, 32);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(130, 399, 162, 41);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Pictures\\saaa (3).jpeg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-3, 0, 460, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // String pass = null;
        try {
           
              DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String ur1="jdbc:oracle:thin:@localhost:1521:xe";
              Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
              con.setAutoCommit(false);
             String username=jTextField1.getText();
             String paas=jPasswordField1.getText();
               pass1=jPasswordField1.getText();
             name =jTextField1.getText();
             Statement stmt=con.createStatement();
             String sql="select * from login where USERNAME='"+username+"' and PASSWORD_LOGIN='"+paas+"'";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
               name1=rs.getString("USERNAME");
                passa=rs.getString("PASSWORD_LOGIN");
                System.out.println(passa);
             }
             if(name.equals(name1)){
                     authenticate();}
             else{
              JOptionPane.showMessageDialog(null,"the user does not exist ");
             
             }
        
        
        }
           
    
       
              
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
        
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         creatuser v=new creatuser();
       v.setVisible(true);
        v.setBounds(0, 0, 420, 710);
        v.setResizable(false);
        v.setTitle("Creat User");
       v.setDefaultCloseOperation(creatuser.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed
   public void authenticate(){
              if("***".equals(passa)){
                  mainapplication o=new  mainapplication();
               o.setVisible(true);
                 o.setBounds(0, 0, 700, 617);
                 o.setResizable(false);
              o.setTitle("Login");
                 o.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
                     this.setVisible(false);}
              else if(pass1.equals(passa)){
                               
                              mainappuser o=new  mainappuser();
                               o.setVisible(true);
                                 o.setBounds(0, 0, 650, 520);
                                       o.setResizable(false);
                               o.setTitle("Login");
                              o.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
                                   this.setVisible(false); 
                             
                             }
              else{
             JOptionPane.showMessageDialog(null,"erorr of the password ");
              
              }


}
   
    /**
     * @param args the command line arguments 
     */
       public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
