/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.babystore;

import static com.mycompany.babystore.mainapplication.ID;
import static com.mycompany.babystore.mainapplication.age;
import static com.mycompany.babystore.mainapplication.fname;
import static com.mycompany.babystore.mainapplication.lname;
import static com.mycompany.babystore.mainapplication.mname;
import static com.mycompany.babystore.mainapplication.phonee;
import static com.mycompany.babystore.product.p1;
import static com.mycompany.babystore.product.p10;
import static com.mycompany.babystore.product.p11;
import static com.mycompany.babystore.product.p12;
import static com.mycompany.babystore.product.p13;
import static com.mycompany.babystore.product.p14;
import static com.mycompany.babystore.product.p15;
import static com.mycompany.babystore.product.p16;
import static com.mycompany.babystore.product.p17;
import static com.mycompany.babystore.product.p18;
import static com.mycompany.babystore.product.p2;
import static com.mycompany.babystore.product.p3;
import static com.mycompany.babystore.product.p4;
import static com.mycompany.babystore.product.p5;
import static com.mycompany.babystore.product.p6;
import static com.mycompany.babystore.product.p7;
import static com.mycompany.babystore.product.p8;
import static com.mycompany.babystore.product.p9;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author TestEnv
 */
public class mainappuser extends javax.swing.JFrame {

    /**
     * Creates new form mainappuser
     */
     public static String ID1;
      public static String fname1;
       public static String mname1;
      public static String lname1;
     public static String phonee1;
     public static String age1;
    public mainappuser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clothes = new javax.swing.JButton();
        game = new javax.swing.JButton();
        game1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        userinfo = new javax.swing.JButton();
        shoppingcart = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        clothes.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\q.jpeg")); // NOI18N
        clothes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothesActionPerformed(evt);
            }
        });
        getContentPane().add(clothes);
        clothes.setBounds(50, 170, 160, 170);

        game.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\g.jpeg")); // NOI18N
        game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameActionPerformed(evt);
            }
        });
        getContentPane().add(game);
        game.setBounds(250, 170, 160, 170);

        game1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\c (1).jpeg")); // NOI18N
        game1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game1ActionPerformed(evt);
            }
        });
        getContentPane().add(game1);
        game1.setBounds(450, 170, 160, 170);

        jLabel2.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("Welcome Baby Store");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 50, 340, 70);

        userinfo.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\user.png")); // NOI18N
        userinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userinfoActionPerformed(evt);
            }
        });
        getContentPane().add(userinfo);
        userinfo.setBounds(0, 0, 60, 57);

        shoppingcart.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\cart.jpg")); // NOI18N
        shoppingcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoppingcartActionPerformed(evt);
            }
        });
        getContentPane().add(shoppingcart);
        shoppingcart.setBounds(573, 6, 60, 57);

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\out.png")); // NOI18N
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(477, 407, 140, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\nnbc.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-3, 0, 650, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shoppingcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoppingcartActionPerformed
        // TODO add your handling code here:
        
        shoppingCart c = new shoppingCart();
        c.show(true);
        c.setBounds(0, 0, 800, 750);
        c.setResizable(false);
        c.setTitle("Shopping Cart");
        c.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_shoppingcartActionPerformed

    private void clothesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothesActionPerformed
        // TODO add your handling code here:
         try {
           DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
           String ur1="jdbc:oracle:thin:@localhost:1521:xe";
               Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
              
             Statement stmt=con.createStatement();
             String sql="select PRODUCT_PRICE from product where PRODUCT_ID="+110011+" ";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                String price= String.valueOf(rs.getDouble("PRODUCT_PRICE"));
                 p1=price;}
              String sql2="select PRODUCT_PRICE from product where PRODUCT_ID="+120011+" ";
             ResultSet rs2= stmt.executeQuery(sql2);
             while(rs2.next()){
                String price= String.valueOf(rs2.getDouble("PRODUCT_PRICE"));
                 p2=price;}
              String sql3="select PRODUCT_PRICE from product where PRODUCT_ID="+130011+" ";
             ResultSet rs3= stmt.executeQuery(sql3);
             while(rs3.next()){
                String price= String.valueOf(rs3.getDouble("PRODUCT_PRICE"));
                 p3=price;}
              String sql4="select PRODUCT_PRICE from product where PRODUCT_ID="+150011+" ";
             ResultSet rs4= stmt.executeQuery(sql4);
             while(rs4.next()){
                String price= String.valueOf(rs4.getDouble("PRODUCT_PRICE"));
                 p4=price;}
              String sql5="select PRODUCT_PRICE from product where PRODUCT_ID="+160011+" ";
             ResultSet rs5= stmt.executeQuery(sql5);
             while(rs5.next()){
                String price= String.valueOf(rs5.getDouble("PRODUCT_PRICE"));
                 p5=price;}
              String sql6="select PRODUCT_PRICE from product where PRODUCT_ID="+170011+" ";
             ResultSet rs6= stmt.executeQuery(sql6);
             while(rs6.next()){
                String price= String.valueOf(rs6.getDouble("PRODUCT_PRICE"));
                 p6=price;}
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
        this.setVisible(false);
         clothesJfram o=new   clothesJfram(p1,p2,p3,p4,p5,p6);
        o.setVisible(true);
        o.setBounds(0, 0, 710, 660);
        o.setResizable(false);
        o.setTitle("clothes");
        o.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
    }//GEN-LAST:event_clothesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        login o=new  login();
        o.setVisible(true);
        o.setBounds(0, 0, 440, 660);
        o.setResizable(false);
        o.setTitle("Login");
        o.setDefaultCloseOperation(login.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void userinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userinfoActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
          login R=new  login();
           String names = R.name;
         try {
           
              DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String ur1="jdbc:oracle:thin:@localhost:1521:xe";
              Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
              con.setAutoCommit(false);
             Statement stmt=con.createStatement();
             String sql="select * from userr,verifyu where verifyu.user_ID=userr.user_ID and USERNAME='"+names+"'";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                  String user_ID= String.valueOf(rs.getInt("user_ID"));
                String Fname=rs.getString("Fname");
                String Minit=rs.getString("Minit");
                String Lname=rs.getString("Lname");
                String phone= String.valueOf(rs.getInt("phone"));
                String email= rs.getString("email");
                 ID1=user_ID;
                 fname1=Fname;
                 mname1=Minit;
                 lname1=Lname;
                 phonee1=phone;
                 age1=email;
                 
               
             }
          user o=new  user(ID1,fname1,mname1,lname1,phonee1,age1);
           o.setVisible(true);
          o.setBounds(0, 0, 410, 400);
           o.setResizable(false);
        o.setTitle("manager");
        o.setDefaultCloseOperation(manager.DISPOSE_ON_CLOSE);
             
       } 
         
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_userinfoActionPerformed

    private void gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameActionPerformed
        // TODO add your handling code here:
         try {
           DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
           String ur1="jdbc:oracle:thin:@localhost:1521:xe";
               Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
              
             Statement stmt=con.createStatement();
             String sql="select PRODUCT_PRICE from product where PRODUCT_ID="+190011+" ";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                String price= String.valueOf(rs.getDouble("PRODUCT_PRICE"));
                 p7=price;}
              String sql2="select PRODUCT_PRICE from product where PRODUCT_ID="+200011+" ";
             ResultSet rs2= stmt.executeQuery(sql2);
             while(rs2.next()){
                String price= String.valueOf(rs2.getDouble("PRODUCT_PRICE"));
                 p8=price;}
              String sql3="select PRODUCT_PRICE from product where PRODUCT_ID="+210011+" ";
             ResultSet rs3= stmt.executeQuery(sql3);
             while(rs3.next()){
                String price= String.valueOf(rs3.getDouble("PRODUCT_PRICE"));
                 p9=price;}
              String sql4="select PRODUCT_PRICE from product where PRODUCT_ID="+230011+" ";
             ResultSet rs4= stmt.executeQuery(sql4);
             while(rs4.next()){
                String price= String.valueOf(rs4.getDouble("PRODUCT_PRICE"));
                 p10=price;}
              String sql5="select PRODUCT_PRICE from product where PRODUCT_ID="+240011+" ";
             ResultSet rs5= stmt.executeQuery(sql5);
             while(rs5.next()){
                String price= String.valueOf(rs5.getDouble("PRODUCT_PRICE"));
                 p11=price;}
              String sql6="select PRODUCT_PRICE from product where PRODUCT_ID="+250011+" ";
             ResultSet rs6= stmt.executeQuery(sql6);
             while(rs6.next()){
                String price= String.valueOf(rs6.getDouble("PRODUCT_PRICE"));
                 p12=price;}
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
         this.setVisible(false);
         gameJfram o=new  gameJfram(p7,p8,p9,p10,p11,p12);
        o.setVisible(true);
        o.setBounds(0, 0, 730, 600);
        o.setResizable(false);
        o.setTitle("games");
        o.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
        
        
        
        
    }//GEN-LAST:event_gameActionPerformed

    private void game1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game1ActionPerformed
        // TODO add your handling code here:
          try {
           DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
           String ur1="jdbc:oracle:thin:@localhost:1521:xe";
               Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
              
             Statement stmt=con.createStatement();
             String sql="select PRODUCT_PRICE from product where PRODUCT_ID="+270011+" ";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                String price= String.valueOf(rs.getDouble("PRODUCT_PRICE"));
                 p13=price;}
              String sql2="select PRODUCT_PRICE from product where PRODUCT_ID="+280011+" ";
             ResultSet rs2= stmt.executeQuery(sql2);
             while(rs2.next()){
                String price= String.valueOf(rs2.getDouble("PRODUCT_PRICE"));
                 p14=price;}
              String sql3="select PRODUCT_PRICE from product where PRODUCT_ID="+290011+" ";
             ResultSet rs3= stmt.executeQuery(sql3);
             while(rs3.next()){
                String price= String.valueOf(rs3.getDouble("PRODUCT_PRICE"));
                 p15=price;}
              String sql4="select PRODUCT_PRICE from product where PRODUCT_ID="+310011+" ";
             ResultSet rs4= stmt.executeQuery(sql4);
             while(rs4.next()){
                String price= String.valueOf(rs4.getDouble("PRODUCT_PRICE"));
                 p16=price;}
              String sql5="select PRODUCT_PRICE from product where PRODUCT_ID="+320011+" ";
             ResultSet rs5= stmt.executeQuery(sql5);
             while(rs5.next()){
                String price= String.valueOf(rs5.getDouble("PRODUCT_PRICE"));
                 p17=price;}
              String sql6="select PRODUCT_PRICE from product where PRODUCT_ID="+330011+" ";
             ResultSet rs6= stmt.executeQuery(sql6);
             while(rs6.next()){
                String price= String.valueOf(rs6.getDouble("PRODUCT_PRICE"));
                 p18=price;}
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
         this.setVisible(false);
        accessoriesJfram o=new accessoriesJfram(p13,p14,p15,p16,p17,p18);
        o.setVisible(true);
        o.setBounds(0, 0, 730, 600);
        o.setResizable(false);
        o.setTitle("Accessories");
        o.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
    }//GEN-LAST:event_game1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainappuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainappuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainappuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainappuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainappuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clothes;
    private javax.swing.JButton game;
    private javax.swing.JButton game1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton shoppingcart;
    private javax.swing.JButton userinfo;
    // End of variables declaration//GEN-END:variables
}
