/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.babystore;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author TestEnv
 */
public class product extends javax.swing.JFrame {

    /**
     * Creates new form product
     */
    public static String p1;
    public static String p2;
    public static String p3;
    public static String p4;
    public static String p5;
    public static String p6;
     public static String p7;
    public static String p8;
    public static String p9;
    public static String p10;
    public static String p11;
    public static String p12;
     public static String p13;
    public static String p14;
    public static String p15;
    public static String p16;
    public static String p17;
    public static String p18;
    
    public product() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\www.png")); // NOI18N
        jLabel1.setText(" Product");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 760, 60);

        jButton4.setBackground(new java.awt.Color(255, 204, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton4.setText(" change of price");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 370, 170, 32);

        jButton5.setBackground(new java.awt.Color(255, 204, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 490, 170, 35);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\q.jpeg")); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\g.jpeg")); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\c (1).jpeg")); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 140, 766, 160);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product_ID", "product_name", "PRODUCT_PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(260, 360, 497, 200);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CLothes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(14, 249, 144, 26);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Games");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 250, 144, 26);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Accessories");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(608, 249, 144, 26);

        jButton6.setBackground(new java.awt.Color(255, 204, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton6.setText("clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 530, 170, 32);

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(180, 370, 19, 32);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 450, 100, 30);

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(30, 410, 100, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Desktop\\nnbc.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-33, -100, 830, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
          try {
           DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
           String ur1="jdbc:oracle:thin:@localhost:1521:xe";
               Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
              
             Statement stmt=con.createStatement();
             String sql="select PRODUCT_PRICE from product where PRODUCT_ID="+110011+" ";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                String price= String.valueOf(rs.getDouble("PRODUCT_PRICE"));
                 p1=price;}
              String sql2="select PRODUCT_PRICE from product where PRODUCT_ID="+120011+" ";
             ResultSet rs2= stmt.executeQuery(sql2);
             while(rs2.next()){
                String price= String.valueOf(rs2.getDouble("PRODUCT_PRICE"));
                 p2=price;}
              String sql3="select PRODUCT_PRICE from product where PRODUCT_ID="+130011+" ";
             ResultSet rs3= stmt.executeQuery(sql3);
             while(rs3.next()){
                String price= String.valueOf(rs3.getDouble("PRODUCT_PRICE"));
                 p3=price;}
              String sql4="select PRODUCT_PRICE from product where PRODUCT_ID="+150011+" ";
             ResultSet rs4= stmt.executeQuery(sql4);
             while(rs4.next()){
                String price= String.valueOf(rs4.getDouble("PRODUCT_PRICE"));
                 p4=price;}
              String sql5="select PRODUCT_PRICE from product where PRODUCT_ID="+160011+" ";
             ResultSet rs5= stmt.executeQuery(sql5);
             while(rs5.next()){
                String price= String.valueOf(rs5.getDouble("PRODUCT_PRICE"));
                 p5=price;}
              String sql6="select PRODUCT_PRICE from product where PRODUCT_ID="+170011+" ";
             ResultSet rs6= stmt.executeQuery(sql6);
             while(rs6.next()){
                String price= String.valueOf(rs6.getDouble("PRODUCT_PRICE"));
                 p6=price;}
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
        this.setVisible(false);
         clothes o=new  clothes(p1,p2,p3,p4,p5,p6);
        o.setVisible(true);
        o.setBounds(0, 0, 620, 660);
        o.setResizable(false);
        o.setTitle("clothes");
        o.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
           DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
           String ur1="jdbc:oracle:thin:@localhost:1521:xe";
               Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
              
             Statement stmt=con.createStatement();
             String sql="select PRODUCT_PRICE from product where PRODUCT_ID="+190011+" ";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                String price= String.valueOf(rs.getDouble("PRODUCT_PRICE"));
                 p7=price;}
              String sql2="select PRODUCT_PRICE from product where PRODUCT_ID="+200011+" ";
             ResultSet rs2= stmt.executeQuery(sql2);
             while(rs2.next()){
                String price= String.valueOf(rs2.getDouble("PRODUCT_PRICE"));
                 p8=price;}
              String sql3="select PRODUCT_PRICE from product where PRODUCT_ID="+210011+" ";
             ResultSet rs3= stmt.executeQuery(sql3);
             while(rs3.next()){
                String price= String.valueOf(rs3.getDouble("PRODUCT_PRICE"));
                 p9=price;}
              String sql4="select PRODUCT_PRICE from product where PRODUCT_ID="+230011+" ";
             ResultSet rs4= stmt.executeQuery(sql4);
             while(rs4.next()){
                String price= String.valueOf(rs4.getDouble("PRODUCT_PRICE"));
                 p10=price;}
              String sql5="select PRODUCT_PRICE from product where PRODUCT_ID="+240011+" ";
             ResultSet rs5= stmt.executeQuery(sql5);
             while(rs5.next()){
                String price= String.valueOf(rs5.getDouble("PRODUCT_PRICE"));
                 p11=price;}
              String sql6="select PRODUCT_PRICE from product where PRODUCT_ID="+250011+" ";
             ResultSet rs6= stmt.executeQuery(sql6);
             while(rs6.next()){
                String price= String.valueOf(rs6.getDouble("PRODUCT_PRICE"));
                 p12=price;}
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
         this.setVisible(false);
         games o=new  games(p7,p8,p9,p10,p11,p12);
        o.setVisible(true);
        o.setBounds(0, 0, 620, 600);
        o.setResizable(false);
        o.setTitle("games");
        o.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
           DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
           String ur1="jdbc:oracle:thin:@localhost:1521:xe";
               Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
              
             Statement stmt=con.createStatement();
             String sql="select PRODUCT_PRICE from product where PRODUCT_ID="+270011+" ";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                String price= String.valueOf(rs.getDouble("PRODUCT_PRICE"));
                 p13=price;}
              String sql2="select PRODUCT_PRICE from product where PRODUCT_ID="+280011+" ";
             ResultSet rs2= stmt.executeQuery(sql2);
             while(rs2.next()){
                String price= String.valueOf(rs2.getDouble("PRODUCT_PRICE"));
                 p14=price;}
              String sql3="select PRODUCT_PRICE from product where PRODUCT_ID="+290011+" ";
             ResultSet rs3= stmt.executeQuery(sql3);
             while(rs3.next()){
                String price= String.valueOf(rs3.getDouble("PRODUCT_PRICE"));
                 p15=price;}
              String sql4="select PRODUCT_PRICE from product where PRODUCT_ID="+310011+" ";
             ResultSet rs4= stmt.executeQuery(sql4);
             while(rs4.next()){
                String price= String.valueOf(rs4.getDouble("PRODUCT_PRICE"));
                 p16=price;}
              String sql5="select PRODUCT_PRICE from product where PRODUCT_ID="+320011+" ";
             ResultSet rs5= stmt.executeQuery(sql5);
             while(rs5.next()){
                String price= String.valueOf(rs5.getDouble("PRODUCT_PRICE"));
                 p17=price;}
              String sql6="select PRODUCT_PRICE from product where PRODUCT_ID="+330011+" ";
             ResultSet rs6= stmt.executeQuery(sql6);
             while(rs6.next()){
                String price= String.valueOf(rs6.getDouble("PRODUCT_PRICE"));
                 p18=price;}
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
         this.setVisible(false);
         Accessories o=new  Accessories(p13,p14,p15,p16,p17,p18);
        o.setVisible(true);
        o.setBounds(0, 0, 620, 640);
        o.setResizable(false);
        o.setTitle("Accessories");
        o.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        mainapplication o=new  mainapplication();
        o.setVisible(true);
        o.setBounds(0, 0, 700, 617);
        o.setResizable(false);
        o.setTitle("STORE");
        o.setDefaultCloseOperation( mainapplication.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setToolTipText("show all clothes");
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
         jButton1.setToolTipText("show all games");
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
         jButton3.setToolTipText("show all Accessories");
    }//GEN-LAST:event_jButton3MouseEntered

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
        try {
           DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
           String ur1="jdbc:oracle:thin:@localhost:1521:xe";
          Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
              con.setAutoCommit(false);
             Statement stmt=con.createStatement();
             String sql="select * from product";
             ResultSet rs= stmt.executeQuery(sql);
             while(rs.next()){
                String pro_ID= String.valueOf(rs.getInt("PRODUCT_ID"));
                String name=rs.getString("PRODUCT_NAME");
                String price= String.valueOf(rs.getDouble("PRODUCT_PRICE"));
                String tbdata[] = {pro_ID,name,price};
                DefaultTableModel tblModel=(DefaultTableModel)jTable3.getModel();
                  tblModel.addRow(tbdata);
                 
             }
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }}
        else{
                jTable3.setModel(new DefaultTableModel(null,new String[]{"pro_ID","name","price"}));

        }
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       
          
       try {
           DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
           String ur1="jdbc:oracle:thin:@localhost:1521:xe";
          Connection con=DriverManager.getConnection(ur1, "c##nancysawa", "654321");
             Statement stmt=con.createStatement();
               int number = Integer.parseInt(jTextField2.getText());
                double number1 = Double.parseDouble(jTextField1.getText());
              String sql="update product set PRODUCT_PRICE = "+number1+" where PRODUCT_ID= "+number+"";
              PreparedStatement up=con.prepareStatement(sql);
               up.execute();
             
              JOptionPane.showMessageDialog(null,"DONE to update ");
             
       } 
       catch (SQLException ex) {
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
       }
       
       
       
       
       
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        int i=jTable3.getSelectedRow();
        TableModel mode1=jTable3.getModel();
        jTextField2.setText(mode1.getValueAt(i,0).toString());
        jTextField1.setText(mode1.getValueAt(i,2).toString());
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         jTable3.setModel(new DefaultTableModel(null,new String[]{"pro_ID","name","price"}));
         jTextField1.setText("");
         jTextField2.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
